if: branch = master OR branch =~ ^release/ OR tag IS present
language: go
go: 1.9
sudo: true
git:
  depth: false
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
# Make sure gcloud command is on our PATH and the App Engine SDK is in the Python path
- PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
# [START auth]
- openssl aes-256-cbc -K $encrypted_3a0414e700dd_key -iv $encrypted_3a0414e700dd_iv
  -in pulumi-gcloud-credentials.json.enc -out pulumi-gcloud-credentials.json -d
  # If the SDK is not already cached, download it and unpack it
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
# Here we use the decrypted service account credentials to authenticate the command line tool
- gcloud auth activate-service-account --key-file pulumi-gcloud-credentials.json
# [END auth]
- export GOOGLE_APPLICATION_CREDENTIALS=./pulumi-gcloud-credentials.json
- export PULUMI_ROOT=/opt/pulumi
- go get -v github.com/golang/dep/cmd/dep
- go get -v github.com/alecthomas/gometalinter
- gometalinter --install
- nvm install v6.10.2
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
- export PATH=$HOME/.yarn/bin:$PATH
- pip install --upgrade --user twine==1.9.1
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
- mkdir -p ~/.config/pip && echo -e "[global]\nextra-index-url = https://${PULUMI_API_TOKEN}@pypi.pulumi.com/simple"
- pip install --upgrade --user awscli
install:
- git clone git@github.com:pulumi/home ${GOPATH}/src/github.com/pulumi/home
- "${GOPATH}/src/github.com/pulumi/home/scripts/install-locked.sh ${PULUMI_ROOT} pulumi"
- make ensure
script:
- make travis_${TRAVIS_EVENT_TYPE}
notifications:
  webhooks: https://ufci1w66n3.execute-api.us-west-2.amazonaws.com/stage/travis
