[[constraint]]
  name = "github.com/pulumi/pulumi-terraform"
  branch = "joeduffy/skip_markdown_header_fix"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-google"
  source = "github.com/pulumi/terraform-provider-google"
  branch = "pulumi-master"
