[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi-terraform"

[[constraint]]
  version = "v1.20.0"
  name = "github.com/terraform-providers/terraform-provider-google-beta"

  [constraint.metadata]
    govendor-override = true
    govendor-exclude-prefixes = [
      "github.com/golang/protobuf",
    ]

