[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi-terraform"

[[constraint]]
  branch = "master"
  name = "github.com/terraform-providers/terraform-provider-google-beta"
  [constraint.metadata]
    gomod-override = true

